[features]
seeds = false
skip-lint = false

[programs.localnet]
jupiter_rewards = "BxT5WsUYEDAfiJ9zHZ6U5oDBZZA5AUMXS41mg1KRv78q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
solana-program = "1.16.0"
