[features]
seeds = false
skip-lint = false

[programs.mainnet]
jupiter_rewards = "JupRwdXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create-token = "ts-node scripts/create-token.ts"
initialize = "ts-node scripts/initialize-program.ts"
swap-distribute = "ts-node scripts/swap-and-distribute.ts" 